airium="0.2.5"
amqp="5.1.1"
async-timeout="4.0.2"
attrs="22.2.0"
billiard="3.6.4.0"
cachetools="5.2.0"
certifi="2022.12.7"
charset-normalizer="2.1.1"
click="8.1.3"
click-didyoumean="0.3.0"
click-plugins="1.1.1"
click-repl="0.2.0"
colorama="0.4.6"
et-xmlfile="1.1.0"
exceptiongroup="1.1.0"
Flask="2.2.2"
Flask-Login="0.6.2"
Flask-SQLAlchemy="3.0.2"
google-api-core="2.11.0"
google-api-python-client="2.70.0"
google-auth="2.15.0"
google-auth-httplib2="0.1.0"
googleapis-common-protos="1.57.0"
greenlet="2.0.1"
gunicorn="20.1.0"
httplib2="0.21.0"
idna="3.4"
importlib-metadata="5.2.0"
iniconfig="1.1.1"
itsdangerous="2.1.2"
Jinja2="3.1.2"
kombu="5.2.4"
MarkupSafe="2.1.1"
numpy="1.24.0"
openai="0.25.0"
openpyxl="3.0.10"
packaging="22.0"
pandas="1.5.2"
pandas-stubs="1.5.2.221213"
pluggy="1.0.0"
prompt-toolkit="3.0.36"
protobuf="4.21.12"
pyasn1="0.4.8"
pyasn1-modules="0.2.8"
pyparsing="3.0.9"
python-dateutil="2.8.2"
pytz="2022.7"
redis="4.4.0"
requests="2.28.1"
rsa="4.9"
six="1.16.0"
spotipy="2.22.0"
SQLAlchemy="1.4.45"
tomli="2.0.1"
tqdm="4.64.1"
types-pytz="2022.7.0.0"
typing_extensions="4.4.0"
uritemplate="4.1.1"
urllib3="1.26.13"
vine="5.0.0"
wcwidth="0.2.5"
Werkzeug="2.2.2"
zipp="3.11.0"
